spring:
  application:
    name: biblioteca
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost/biblioteca
    username: boracodardevs
    password: boracodardevs
    driver-class-name: org.postgresql.Driver
